name: C/C++ CI

on:
  workflow_dispatch:
  push:
    branches: [ "main","develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: cmake -DCMAKE_BUILD_TYPE="Release" -DCMAKE_INSTALL_PREFIX="./tiznitbms/" -S . -B build
    - name: build
      run: cmake --build build
    - name: install
      run: cmake --install build
    - name: archive-binary
      uses: actions/upload-artifact@v4
      with:
          name: tiznitbms-linux
          path: ./tiznitbms/

  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: cmake -DCMAKE_BUILD_TYPE="Release" -DCMAKE_INSTALL_PREFIX="./tiznitbms/" -S . -B build
    - name: build
      run: cmake --build build
    - name: install
      run: cmake --install build
    - name: archive-binary
      uses: actions/upload-artifact@v4
      with:
          name: tiznitbms-macos
          path: ./tiznitbms/

  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: cmake -DCMAKE_INSTALL_PREFIX="./tiznitbms/" -S . -B build
    - name: build
      run: cmake --build build --config Release
    - name: install
      run: cmake --install build
    - name: archive-binary
      uses: actions/upload-artifact@v4
      with:
          name: tiznitbms-windows
          path: ./tiznitbms/
